---
name: flutter_todo_list
description: "Yet another todo list, made with Flutter and DRF."
version: 1.0.0+1
environment:
  sdk: ">=2.18.5 <3.0.0"
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^7.0.1
  go_router: ^6.0.0
  openapi:
    path: lib/openapi
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
