// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZjgRmVxkH_V8DDBXeuYs0Nxr3Mf_X7h4',
    appId: '1:858738813212:android:db9666bcea599949f5b2d9',
    messagingSenderId: '858738813212',
    projectId: 'flutter-todo-list-3b9ed',
    storageBucket: 'flutter-todo-list-3b9ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzHTZy9blIdsdEIp0vXJ5PUyRjW2quBkI',
    appId: '1:858738813212:ios:29fcd365d7a9f5b8f5b2d9',
    messagingSenderId: '858738813212',
    projectId: 'flutter-todo-list-3b9ed',
    storageBucket: 'flutter-todo-list-3b9ed.appspot.com',
    iosClientId: '858738813212-utel0cgukcsdvr6krq5hcjmjgcjpgo3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoList',
  );
}
